Repository JulSaMo/CS-start, pull requests merged in 2022-08, with the labels that each got.

#1 [Add] 캐시메모리 내용 업로드
  Computer Science/Computer Architecture/캐시 메모리 (Cache Memory).md
Labels: CA, 브라운🧸

#2 [Add] 고정소수점 부동소수점 내용 업로드
  Computer Science/Computer Architecture/실수표현방식 (고정 소수점과 부동 소수점).md
Labels: CA, 브라운🧸

#3 [ADD] 컴퓨터 구조 기초 내용 업로드
  Computer Science/Computer Architecture/컴퓨터 구조 기초.md
Labels: CA, 에이든🅰️

#4 [Add] 컴퓨터구조(Computer Architecture).
  Computer Science/Computer Architecture/02.컴퓨터구조(Computer Architecture).md
Labels: CA, 노엘🎤

#8 [Add] Array (배열) 내용 업로드
  Computer Science/Data Structure/Array(배열).md
Labels: DS, 브라운🧸

#9 [Add] linked list 연결리스트 내용 업로드
  Computer Science/Data Structure/Linked List (연결리스트).md
Labels: DS, 브라운🧸

#10 [Add] Array vs. ArrayList vs. LinkedList 비교 내용 업로드
  Computer Science/Data Structure/Array, Array List, Linked List 차이점.md
Labels: DS, 브라운🧸

#12 [Add] 트라이(trie) 자료구조
  Computer Science/Data Structure/Trie.md
Labels: DS, 노엘🎤

#14 [Add] Stack, Queue 내용 업로드
  Computer Science/Data Structure/stack&queue.md
  Computer Science/Data Structure/temp.md
Labels: DS, 에이든🅰️

#23 [Add] 정규화(Nomalization) 내용 업로드
  Computer Science/Database/정규화(Nomalization).md
Labels: DB, 브라운🧸

#24 [Add] 이상(Anomaly) 내용 업로드
  Computer Science/Database/이상(Anomaly).md
Labels: DB, 브라운🧸

#5 [Add] ARM Process
  Computer Science/Computer Architecture/ARM Process.md
Labels: CA, 잭🦭

#18 [Add] SQL-join
  Computer Science/Database/[DB] SQL-join.md
Labels: DB, 잭🦭

#19 [Add] Key
  Computer Science/Database/[DB] Key.md
Labels: DB, 잭🦭

#21 [Add] SQL-vs-NoSQL
  Computer Science/Database/[DB] SQL-vs-NoSQl.md
Labels: DB, 잭🦭

#25 [Add] 인덱스(INDEX) 내용 업로드
  Computer Science/Database/Index.md
Labels: DB, 노엘🎤

#26 [Add] 트랜잭션(Transaction) 업로드
  Computer Science/Database/Transaction.md
Labels: DB, 노엘🎤

#27 [Add] 트랜잭션 격리수준(transaction isolation level) 업로드
  Computer Science/Database/Transaction Isolation Level.md
Labels: DB, 노엘🎤

#7 [Add] tree & binary tree
  Computer Science/Data Structure/tree-&-binary-tree.md
Labels: DS, 잭🦭

#13 [Add] btree & b+tree
  Computer Science/Data Structure/btree-&-b+tree.md
Labels: DS, 잭🦭
