Repository JulSaMo/CS-start, pull requests merged in 2022-09, with the labels that each got.

#35 [Add] block IO / non block IO
  Computer Science/Network/Block, Non-Block IO.md
Labels: NW, 루키🐥

#29 [Add] block, non block / 동기, 비동기 업로드
  Computer Science/Network/동기, 비동기 개념(synchronous vs asynchronous).md
Labels: NW, 루키🐥

#30 [Add] Symmetric Key & Public Key (대칭키와 공개키) 내용 업로드
  Computer Science/Network/Symmetric Key & Public Key (대칭키와 공개키).md
Labels: NW, 브라운🧸

#31 [Add] http와 https 내용 업로드
  Computer Science/Network/http와 https.md
Labels: NW, 브라운🧸

#32 [Add] TLS, SSL 차이 내용 업로드
  Computer Science/Network/TLS, SSL.md
Labels: NW, 브라운🧸

#34 [Add] Load balancing 내용 업로드
  Computer Science/Network/Load Balancing.md
Labels: NW, 노엘🎤

#33 [Add] OSI 7계층 업로드
  Computer Science/Network/OSI 7 Layer.md
Labels: NW, 노엘🎤

#37 [Add] tcp ip control flow&control congestion
  Computer Science/Network/tcp3&4wa/tcpIpControlFlow&Congestion(흐름&혼잡제어).md
Labels: NW, 잭🦭

#36 [Add] tcp3way&tcp4way
  Computer Science/Network/tcp3&4way(전송제어프로그램).md
Labels: NW, 잭🦭

#38 [Add] tcpVsUdp 내용 정리
  Computer Science/Network/tcpVsUdp.md
Labels: NW, 잭🦭

#39 [ADD] CPU Scheduling
  Computer Science/Operating System/CPU Scheduling.md
Labels: OS, 루키🐥

#40 [Add] DeadLock
  Computer Science/Operating System/DeadLock.md
Labels: OS, 루키🐥

#41 [Add] RareCondition
  Computer Science/Operating System/Rare Condition.md
Labels: OS, 루키🐥

#54 [Add] 세마포어, 뮤텍스 내용 업로드
  Computer Science/Operating System/Semaphore, Mutex(세마포어, 뮤텍스).md
Labels: OS, 브라운🧸

#53 [Add] IPC 내용 업로드
  Computer Science/Operating System/IPC.md
Labels: OS, 브라운🧸

#42 [Add] Memory
  Computer Science/Operating System/memory.md
Labels: OS, 잭🦭

#52 [Add] PCB와 Context Switching(문맥교환) 내용 업로드
  Computer Science/Operating System/PCB와 Context Switching(문맥교환).md
Labels: OS, 브라운🧸

#43 [ADD] PagingReplacementAlgorithm
  Computer Science/Operating System/pagingReplacementAlgorithm.md
Labels: OS, 잭🦭

#51 [Add] SystemCall(시스템콜, 시스템호출) 내용 업로드
  Computer Science/Operating System/SystemCall(시스템콜, 시스템호출).md
Labels: OS, 브라운🧸

#44 [Add] Paging&Segmentation
  Computer Science/Operating System/PagingSegmentation.md
Labels: OS, 잭🦭

#45 [Add] File System
  Computer Science/Operating System/fileSystem.md
Labels: OS, 잭🦭

#49 Os/interrupt
  Computer Science/Operating System/인터럽트.md
Labels: OS, 노엘🎤

#47 [Add]process&thread 내용 업로드
  Computer Science/Operating System/프로세스vs스레드.md
Labels: OS, 노엘🎤

#46 [Add]operating system 내용 업로드
  Computer Science/Operating System/운영체제.md
Labels: OS, 노엘🎤

#56 [Add] TDD(TestDrivenDevelopment)
  Computer Science/Software Engineering/TDD&UnitTest.md
Labels: SE, 루키🐥

#59 [Add] DevOps
  Computer Science/Software Engineering/DevOps.md
Labels: SE, 루키🐥

#55 [Add] 객체지향 프로그래밍 (OOP) 내용 업로드
  Computer Science/Software Engineering/객체지향 프로그래밍 (OOP).md
Labels: SE, 브라운🧸

#60 [Add] 함수형 프로그래밍 (Functional Programming) 내용 업로드
  Computer Science/Software Engineering/함수형 프로그래밍 (Functional Programming).md
Labels: SE, 브라운🧸
